# This contains the global configuration of your component.
# environment:
#    jid: your.component.jid
#    password: your.component.password
#    host: host on which the XMPP server is running
#    port: port to which your component should connect
#    application_type: client | component (by default it is component and we strongly discourage any client application in production)

development:
    jid: user@server.com
    password: password
    application_type: client
    auto-reconnect: true

test:
    jid: component.server.com
    password: password
    host: localhost
    port: 5278
    auto-reconnect: true
        
production:
    jid: component.server.com
    password: password
    host: localhost
    port: 5278
    auto-reconnect: true
